### ISSUE TITLE
NameError: uninitialized constant JSON::JWT

### ISSUE THREAD

**Issue by prokopsimek** [datamolecule/letsencrypt_http_challenge#4]
if running rake task:

```
LE_HTTP_CHALLENGE_CONTACT_EMAIL=info@example.com LE_HTTP_CHALLENGE_CERTIFICATE_DOMAINS="www.example.com" bundle exec rake generate_letsencrypt_cert
```

i got error:

```
Registering with Let's Encrypt service...
rake aborted!
NameError: uninitialized constant JSON::JWT
/home/prokop/.rvm/gems/ruby-2.2.4/gems/acme-client-0.3.7/lib/acme/client/crypto.rb:9:in `generate_signed_jws'
/home/prokop/.rvm/gems/ruby-2.2.4/gems/acme-client-0.3.7/lib/acme/client/faraday_middleware.rb:15:in `call'
/home/prokop/.rvm/gems/ruby-2.2.4/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
/home/prokop/.rvm/gems/ruby-2.2.4/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
/home/prokop/.rvm/gems/ruby-2.2.4/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
/home/prokop/.rvm/gems/ruby-2.2.4/gems/acme-client-0.3.7/lib/acme/client.rb:42:in `register'
/home/prokop/.rvm/gems/ruby-2.2.4/gems/letsencrypt_http_challenge-0.0.2/lib/tasks/letsencrypt_http_challenge_tasks.rake:32:in `generate_cert'
/home/prokop/.rvm/gems/ruby-2.2.4/gems/letsencrypt_http_challenge-0.0.2/lib/tasks/letsencrypt_http_challenge_tasks.rake:85:in `block in <top (required)>'
/home/prokop/.rvm/gems/ruby-2.2.4/gems/airbrake-5.4.2/lib/airbrake/rake/task_ext.rb:19:in `execute'
/home/prokop/.rvm/gems/ruby-2.2.4/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/home/prokop/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `eval'
/home/prokop/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => generate_letsencrypt_cert
(See full trace by running task with --trace)
```

traced:

```
** Invoke generate_letsencrypt_cert (first_time)
** Execute generate_letsencrypt_cert
Registering with Let's Encrypt service...
rake aborted!
NameError: uninitialized constant JSON::JWT
/home/prokop/.rvm/gems/ruby-2.2.4/gems/acme-client-0.3.7/lib/acme/client/crypto.rb:9:in `generate_signed_jws'
/home/prokop/.rvm/gems/ruby-2.2.4/gems/acme-client-0.3.7/lib/acme/client/faraday_middleware.rb:15:in `call'
/home/prokop/.rvm/gems/ruby-2.2.4/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
/home/prokop/.rvm/gems/ruby-2.2.4/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
/home/prokop/.rvm/gems/ruby-2.2.4/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
/home/prokop/.rvm/gems/ruby-2.2.4/gems/acme-client-0.3.7/lib/acme/client.rb:42:in `register'
/home/prokop/.rvm/gems/ruby-2.2.4/gems/letsencrypt_http_challenge-0.0.2/lib/tasks/letsencrypt_http_challenge_tasks.rake:32:in `generate_cert'
/home/prokop/.rvm/gems/ruby-2.2.4/gems/letsencrypt_http_challenge-0.0.2/lib/tasks/letsencrypt_http_challenge_tasks.rake:85:in `block in <top (required)>'
/home/prokop/.rvm/gems/ruby-2.2.4/gems/rake-11.2.2/lib/rake/task.rb:248:in `call'
/home/prokop/.rvm/gems/ruby-2.2.4/gems/rake-11.2.2/lib/rake/task.rb:248:in `block in execute'
/home/prokop/.rvm/gems/ruby-2.2.4/gems/rake-11.2.2/lib/rake/task.rb:243:in `each'
/home/prokop/.rvm/gems/ruby-2.2.4/gems/rake-11.2.2/lib/rake/task.rb:243:in `execute'
/home/prokop/.rvm/gems/ruby-2.2.4/gems/airbrake-5.4.2/lib/airbrake/rake/task_ext.rb:19:in `execute'
/home/prokop/.rvm/gems/ruby-2.2.4/gems/rake-11.2.2/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
/home/prokop/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/home/prokop/.rvm/gems/ruby-2.2.4/gems/rake-11.2.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
/home/prokop/.rvm/gems/ruby-2.2.4/gems/rake-11.2.2/lib/rake/task.rb:173:in `invoke'
/home/prokop/.rvm/gems/ruby-2.2.4/gems/rake-11.2.2/lib/rake/application.rb:152:in `invoke_task'
/home/prokop/.rvm/gems/ruby-2.2.4/gems/rake-11.2.2/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/home/prokop/.rvm/gems/ruby-2.2.4/gems/rake-11.2.2/lib/rake/application.rb:108:in `each'
/home/prokop/.rvm/gems/ruby-2.2.4/gems/rake-11.2.2/lib/rake/application.rb:108:in `block in top_level'
/home/prokop/.rvm/gems/ruby-2.2.4/gems/rake-11.2.2/lib/rake/application.rb:117:in `run_with_threads'
/home/prokop/.rvm/gems/ruby-2.2.4/gems/rake-11.2.2/lib/rake/application.rb:102:in `top_level'
/home/prokop/.rvm/gems/ruby-2.2.4/gems/rake-11.2.2/lib/rake/application.rb:80:in `block in run'
/home/prokop/.rvm/gems/ruby-2.2.4/gems/rake-11.2.2/lib/rake/application.rb:178:in `standard_exception_handling'
/home/prokop/.rvm/gems/ruby-2.2.4/gems/rake-11.2.2/lib/rake/application.rb:77:in `run'
/home/prokop/.rvm/gems/ruby-2.2.4/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/home/prokop/.rvm/gems/ruby-2.2.4/bin/rake:23:in `load'
/home/prokop/.rvm/gems/ruby-2.2.4/bin/rake:23:in `<main>'
/home/prokop/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `eval'
/home/prokop/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => generate_letsencrypt_cert
```

gemfile:

```
gem 'letsencrypt_http_challenge'
gem 'json-jwt'
```

Rails 4.2.4
ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux]

**Comment by luclussier** [comment]
Will take a look; in the meantime, have you tried to use an older version of acme-client? 0.3.7 was released just a few days ago.

**Comment by luclussier** [comment]
@prokopsimek Is this still an issue? 
Do you have json-jwt under /home/prokop/.rvm/gems/ruby-2.2.4/gems/ ?
I have tried to mirror a similar setup but did not get any error using json-jwt 1.2.3 and 1.6.3...

Unless you are using it in your rails app, 'json-jwt' is already a dependency of acme-client so you would not need to include it in your Gemfile.
